# Generated by Django 2.0.6 on 2018-06-18 06:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('many_to_many', '0005_twitteruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitterUser',
            new_name='InstagramUser',
        ),
    ]
